language: python

python:
  - "3.6"

os:
  - linux
  - osx

before_install:
  # install dependencies for acoustid
  - sudo apt-get update -qq
  # - sudo apt-get install -qq ffmpeg
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - ffmpeg -hwaccels
  - sudo apt-get install -qq python-gst0.10-dev
  - sudo apt-get install -qq chromaprint
  - sudo apt-get install -qq gstreamer1.0
  - sudo apt-get install -qq python-gi
  - sudo apt-get install -qq libchromaprint-tools
  - sudo apt-get install -qq python-gst-1.0
 
install: 
  - sudo pip3 install -r requirements.txt
  - python3 setup.py -q install

script: pytest

